--- # tasks file for spark_proj

      ####################### Update /etc/hosts file     ##################

    - include: etchost.yaml
      ####################### Update /etc/hosts file     ##################
    
    
    - name: remove data dir
      shell: "rm -rf {{spark_usr_parent_dir}}/spark*"
    
    - name: Restore dir
      shell: "cp -R {{spark_usr_parent_dir}}/data_backup/spark-{{spark_version}}  {{spark_usr_parent_dir}}"
      cp -R spark-3.0.1-bin-hadoop3.2/ /usr/lib
      ignore_errors: yes  
  


    - name: start spark master service
      become: true
      become_user: '{{spark_user}}'
      shell: "sbin/start-all.sh"
      args:
        chdir: "{{spark_usr_parent_dir}}/spark/"
      ignore_errors: no
      when: inventory_hostname in groups['tag_Env_Master']
           
 
    - name: start spark history server service
      become: true
      become_user: '{{spark_user}}'
      shell: "sbin/start-history-server.sh"
      args:
        chdir: "{{spark_usr_parent_dir}}/spark/"
      ignore_errors: yes
      when: inventory_hostname in groups['tag_Env_Master']













      
